// <auto-generated />
using System;
using ForLimestone.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForLimestone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForLimestone.Models.CompanyUsers_IP_address", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("CompanyUsersIP");
                });

            modelBuilder.Entity("ForLimestone.Models.IP_address", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyUsers_IP_addressID");

                    b.Property<string>("IPaddress");

                    b.HasKey("ID");

                    b.HasIndex("CompanyUsers_IP_addressID");

                    b.ToTable("IPaddresses");
                });

            modelBuilder.Entity("ForLimestone.Models.IP_address", b =>
                {
                    b.HasOne("ForLimestone.Models.CompanyUsers_IP_address")
                        .WithMany("ListUsersIP")
                        .HasForeignKey("CompanyUsers_IP_addressID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
